---
# Source: meetup/templates/mysql-db-storageclass.yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: clone-wordpress-meetup
provisioner: hpe.com/nimble
parameters:
    destroyOnRm: "true"
    mountConflictDelay: "30"
    folder: "kubernetes"
    cloneOf: "wordpress-meetup-1257c48b-580f-11e8-a0d5-e89a8f4ff60e"

