---
# Source: meetup/templates/mysql-db-storageclass.yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: clone-meetup-storage-class-00
provisioner: hpe.com/nimble
parameters:
    destroyOnRm: "true"
    mountConflictDelay: "30"
    folder: "kubernetes"
    cloneOf: "meetup-storage-class-00-54f9558b-5889-11e8-a0d5-e89a8f4ff60e"  #Change this with the pv that you want to clone

