---
# Source: meetup/templates/mysql-db-storageclass.yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: meetup-storage-class-00
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: hpe.com/nimble
parameters:
    thick: "false"
    dedupe: "false"
    perfPolicy: "SQL Server"
    destroyOnRm: "true"
    mountConflictDelay: "30"
    folder: "kubernetes"
    protectionTemplate: "Retain-30Daily"
