apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" .}}-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    #Use this to point to an application
      app: {{ template "fullname" .}}-app
  type: {{ .Values.service.type }}
