apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" .}}-db-service
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: {{ template "fullname" .}}-db
  type: NodePort
